development:
  adapter: postgresql
  encoding: unicode
  database: brianpetro_development
  pool: 5
  username: brian
  password: changeme

test:
  adapter: postgresql
  encoding: unicode
  database: brianpetro_development
  pool: 5
  username: brian
  password: changeme

